version: "3.9"

services:
  web:
    build: .
    container_name: farm_php
    restart: always
    ports:
      - "8000:80"       # Your PHP app will be at http://localhost:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: sanish
      POSTGRES_PASSWORD: sanish123456
      POSTGRES_DB: farm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: my_adminer
    restart: always
    ports:
      - "8080:8080"  # access Adminer at http://localhost:8080
    depends_on:
      - db

volumes:
  pgdata:
